import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
// CloudLinux Passenger automatically sets process.env.PORT
const port = process.env.PORT || 3000;

// Serve the static files generated by Astro in the "dist" directory
app.use(express.static(path.join(__dirname, 'dist')));

// Fallback for SPA routing (if any) or handle 404s
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', '404.html')); 
  // If you don't have a custom 404, it will fallback properly or you can point it to index.html
});

app.listen(port, () => {
  console.log(`Node Server listening on port ${port}`);
});
